version: '3.8'

services:
  deepseek-chatbot:
    build: .
    ports:
      - "5001:5000"
    environment:
      - FLASK_DEBUG=False
      - PORT=5000
    volumes:
      # Mount model cache directory to persist downloaded models
      - model_cache:/root/.cache/huggingface
      # Mount logs directory
      - ./logs:/app/logs
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  model_cache:
    driver: local 